---
title: "Differential Report"
author: "Robert M Flight"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.width = 8,
                      fig.height = 5,
                      fig.dpi = 600)
## target knits Rmds in their own session, so load libraries here.
source(here::here("packages.R"))
## if you want access to the functions you've written
lapply(list.files(here::here("./R"), full.names = TRUE), source)
```

```{r load-targets}
tar_load(c(lipid_measurements,
         lipid_metadata))

tar_load(c(exploration_child, 
           lipids_differential))

```

## Purpose

Do some analysis on our lipidomics data.

## Data

Data is lipidomics data from a wild-type (WT) tissue and then same tissue after introducing a gene knock-out (KO, removing the gene from the genome).

```{r eda, child='doc/exploration_child.Rmd'}

```

### Differential Analysis

Using `limma`, we did a differential analysis of KO / WT.

```{r}
#| label: figure_of_ko_wt
#| fig.cap: "Volcano plot of KO / WT of lipidomics data. Most things are significant because they are actually technical and not biological replicates."
sig_cut = 0.05
lipids_differential = lipids_differential |>
  dplyr::mutate(log_p = -1 * log10(adj.P.Val),
                sig = adj.P.Val <= sig_cut)
lipids_differential |>
  ggplot(aes(x = logFC, y = log_p, color = sig)) +
  geom_point() +
  theme(legend.position = c(0.1, 0.1))
```